AWSTemplateFormatVersion: "2010-09-09"
Description: "sagemaker-handwriting-recognition
  Handwritten text recognition (HTR) OCR with Amazon SageMaker endpoint deployment"
Parameters:
  SolutionPrefix:
    Type: String
  S3BucketName:
    Type: String
  SageMakerIAMRoleArn:
    Type: String
  SageMakerInferenceInstanceType:
    Type: String
  SolutionsS3BucketNamePrefix:
    Type: String
  SolutionName:
    Type: String

Mappings:
  RegionMap:
    ap-east-1:
      "MXNetInference": "763104351884.dkr.ecr.ap-east-1.amazonaws.com/mxnet-inference:1.6.0-gpu-py3"
    ap-northeast-1:
      "MXNetInference": "763104351884.dkr.ecr.ap-northeast-1.amazonaws.com/mxnet-inference:1.6.0-gpu-py3"
    ap-northeast-2:
      "MXNetInference": "763104351884.dkr.ecr.ap-northeast-2.amazonaws.com/mxnet-inference:1.6.0-gpu-py3"
    ap-southeast-1:
      "MXNetInference": "763104351884.dkr.ecr.ap-southeast-1.amazonaws.com/mxnet-inference:1.6.0-gpu-py3"
    ap-southeast-2:
      "MXNetInference": "763104351884.dkr.ecr.ap-southeast-2.amazonaws.com/mxnet-inference:1.6.0-gpu-py3"
    ap-south-1:
      "MXNetInference": "763104351884.dkr.ecr.ap-south-1.amazonaws.com/mxnet-inference:1.6.0-gpu-py3"
    sa-east-1:
      "MXNetInference": "763104351884.dkr.ecr.sa-east-1.amazonaws.com/mxnet-inference:1.6.0-gpu-py3"
    eu-west-1:
      "MXNetInference": "763104351884.dkr.ecr.eu-west-1.amazonaws.com/mxnet-inference:1.6.0-gpu-py3"
    eu-west-2:
      "MXNetInference": "763104351884.dkr.ecr.eu-west-2.amazonaws.com/mxnet-inference:1.6.0-gpu-py3"
    eu-west-3:
      "MXNetInference": "763104351884.dkr.ecr.eu-west-3.amazonaws.com/mxnet-inference:1.6.0-gpu-py3"
    eu-central-1:
      "MXNetInference": "763104351884.dkr.ecr.eu-central-1.amazonaws.com/mxnet-inference:1.6.0-gpu-py3"
    eu-north-1:
      "MXNetInference": "763104351884.dkr.ecr.eu-north-1.amazonaws.com/mxnet-inference:1.6.0-gpu-py3"
    eu-south-1:
      "MXNetInference": "048378556238..dkr.ecr.eu-south-1.amazonaws.com/mxnet-inference:1.6.0-gpu-py3"
    us-east-1:
      "MXNetInference": "763104351884.dkr.ecr.us-east-1.amazonaws.com/mxnet-inference:1.6.0-gpu-py3"
    us-east-2:
      "MXNetInference": "763104351884.dkr.ecr.us-east-2.amazonaws.com/mxnet-inference:1.6.0-gpu-py3"
    us-west-1:
      "MXNetInference": "763104351884.dkr.ecr.us-west-1.amazonaws.com/mxnet-inference:1.6.0-gpu-py3"
    us-west-2:
      "MXNetInference": "763104351884.dkr.ecr.us-west-2.amazonaws.com/mxnet-inference:1.6.0-gpu-py3"
    ca-central-1:
      "MXNetInference": "763104351884.dkr.ecr.ca-central-1.amazonaws.com/mxnet-inference:1.6.0-gpu-py3"
    me-south-1:
      "MXNetInference": "217643126080.dkr.ecr.me-south-1.amazonaws.com/mxnet-inference:1.6.0-gpu-py3"

Resources:
  Endpoint:
    Type: "AWS::SageMaker::Endpoint"
    Properties:
      EndpointName: !Sub "${SolutionPrefix}-demo"
      EndpointConfigName:
        !GetAtt EndpointConfig.EndpointConfigName
        
  EndpointConfig:
    Type: "AWS::SageMaker::EndpointConfig"
    Properties:
      EndpointConfigName: !Sub "${SolutionPrefix}-demo"
      ProductionVariants:
        - InitialInstanceCount: 1
          InitialVariantWeight: 1.0
          InstanceType: !Sub "${SageMakerInferenceInstanceType}"
          ModelName: !GetAtt Model.ModelName
          VariantName: !GetAtt Model.ModelName
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W1200
            reason: Solution does not have KMS encryption enabled by default
 
  Model:
    Type: "AWS::SageMaker::Model"
    Properties:
      ModelName: !Sub "${SolutionPrefix}-demo"
      PrimaryContainer:
        ModelDataUrl: !Sub "s3://${SolutionsS3BucketNamePrefix}-${AWS::Region}/${SolutionName}/build/model.tar.gz"
        Image: !FindInMap [RegionMap, !Ref "AWS::Region", MXNetInference]
        Mode: "SingleModel"
      ExecutionRoleArn: !Ref SageMakerIAMRoleArn